### ISSUE TITLE
Published LSID domain taxonomy.org.au gone

### ISSUE THREAD

**Issue by mdoering** [AtlasOfLivingAustralia/biocache-service#105]
TDWG is considering to revive a LSID resolver. By looking into LSIDs that have been published in publication it was discovered that the domain taxonomy.org.au was inactive. An example LSID is urn:lsid:taxonomy.org.au:TherevidaeMandala:MEI024058. See 
https://github.com/tdwg/infrastructure/issues/60#issuecomment-238387048

Is there a chance to restore this domain to serve a SRV record that leads to a working resolver?

**Comment by nickdos** [comment]
ABRS who maintain the NSL and minted GUIDs were responsible for that domain (not the ALA). You'll have to ask them - https://www.environment.gov.au/science/abrs. Best contact is Anne Fuchs  <Anne.Fuchs@environment.gov.au>. Domain was registered to them but I think it has lapsed due to non-payment of domain...
