### ISSUE TITLE
ScatterplotController does not use cache, hits Solr for every field

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#130]
The current implementation of ScatterplotController does not use the local in-memory cache maintained by SearchIndexDAOImpl. It accesses Solr directly for every field it attempts to find details for.

Although the cache is currently a Set&lt;IndexFieldDTO&gt;, IndexFieldDTO does not override hashCode, so the Set may not be working correctly. This is tracked in issue #129.

Even when hashCode is overridden, ScatterplotController is currently relying on IndexFieldDTO.getName() as its primary key, where IndexFieldDTO.equals relies on IndexFieldDTO.getDownloadName as its primary key. It may be necessary to create a new List cache that does use getDownloadName as primary key so that getName and isStored can be checked independently.

ScatterplotController is also never checking more than one field, even if multiple matched, throwing an exception on the first IndexFieldDTO object it sees if isStored is not true, or the datatype is unsupported.

It may be more correct to check for the first IndexFieldDTO object where getName() matches the desired field name and isStored returns true, and only throw an error if none are found. However, this approach may still require a new List-based cache in SearchIndexDAO to workaround the use of getDownloadName as the primary key right now.

**Comment by adam-collins** [comment]
The multiple SOLR requests were fixed in https://github.com/AtlasOfLivingAustralia/biocache-service/commit/b634fca506aa630efb5b8df71a543be9eb448062

The concerns regarding matching the correct IndexFieldDTO are handled by the current code. getDownloadName is Cassandra related so unrelated to scatterplot and can be null in IndexFieldDTOs. There can only be one isStored=true for each unique getName.
