### ISSUE TITLE
Zooming with mousewheel in leaflet 

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/biocache-service#152]
When viewing [a map in spatial portal](http://spatial.ala.org.au/?q=lsid%3Ahttp%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2914704), the mousewheel can be used to zoom in/out. This functionality does not seem to be enabled for [leaflet maps](http://biocache.ala.org.au/occurrences/search?q=lsid:http://id.biodiversity.org.au/node/apni/2914704&fq=#tab_mapView). 

Would you consider implementing mousewheel zoom on the latter?

**Comment by nickdos** [comment]
Hi John, thanks for raising this issue. I'm assuming you are talking about the Leaflet map on the Occurrence Records result page. E.g.

http://biocache.ala.org.au/occurrences/search?q=species_group%3AAngiosperms+cl1048%3APilbara&qc=data_hub_uid:dh9#tab_mapView

If so, then I can tell you that we deliberately disabled the mousewheel option as it made the page difficult to use for many users. The reason is, this page is design as a scrollable page and so the user can easily get confused about what they are scrolling, depending on whether the cursor is over the map or not. What tends to happen is the user starts scrolling the page (as any normal web page would - usually to view the facets on the left), but as the content moves down the screen and the cursor "falls" over the map area, the page stops scrolling and the map starts zooming wildly. This can be frustrating to users. The Spatial Portal is designed as a fixed layout and there is no page scrolling, so the mousewheel option makes sense. 

A work around is to use the "shift" + "drag a box" motion on the map with the mouse, which quickly and accurately zooms the map to the desired perspective. You can also double click the map to zoom in quickly.

I hope this answers your question.

**Comment by johnbaums** [comment]
Thanks @nickdos. I figured it may have been an accessibility consideration, and I agree that scrolling maps can be annoying when trying to scroll a webpage (esp. on mobile devices!). Thanks for the shift+drag tip - that's perfect!
