### ISSUE TITLE
matched_children_name searches not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#162]
E.g. http://biocache.ala.org.au/ws/occurrences/search?q=matched_children_name:Acacia  

returns 0 results, whereas

http://biocache.ala.org.au/ws/occurrences/search?q=taxon_name:Acacia

returns 10025 results.

Something has changed to break this...

**Comment by nickdos** [comment]
http://avh-test.ala.org.au/occurrences/search?q=qid:1495779678071

sems to work

**Comment by djtfmartin** [comment]
@nickdos do we remember the expected behaviour for the "matched_children_name" ?

i cant remember what it does...

**Comment by nickdos** [comment]
I had to ask @adam-collins too ;-) It is the same as a LSID: search except it takes a name, thus it includes child taxa.

**Comment by adam-collins** [comment]
The correct field name is matched_name_children:. The linked avh-hub issue has it correct.

I thought it was fixed but it turns out that unlike my local environment production is not following the 301 from the name lookup request, http://bie.ala.org.au/ws/species/Acacia, and it is returning the same result as taxon_name: because it fails to get the lsid.

If that 301 is followed the children species are included as they are with lsid:.

**Comment by adam-collins** [comment]
biocache-service is not following the redirect when the protocol changes. biocache is using service.bie.ws.url=https://bie.ala.org.au/ws

bie-index is setting the protocol to the same as grails.serverURL when redirecting and this is currently http instead of identical to the request.

Changing biocache service.bie.ws.url to match bie-index grails.serverURL has fixed this problem. http://biocache.ala.org.au/ws/occurrences/search?q=matched_name_children:Acacia&facet=off&pageSize=0 now returns a much larger number of occurrences than http://biocache.ala.org.au/ws/occurrences/search?q=taxon_name:Acacia&facet=off&pageSize=0
