### ISSUE TITLE
Downloads: remove column if all values are "NULL"

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#215]
Requested by @Tasilee:

> One issue that would seem reasonably easy to implement in Export is the removal of all columns/fields that have all NULL values (across all records). In many cases, this would reduce the size of the matrix considerably, making it easier to understand and deal with. Having this as a 'check box' on the custom download would seem a 'no-brainer' as the Americans would say.

**Comment by javier-molina** [comment]
In order to determine which fields are empty it is required to go through all the records first as there is no direct way to find that upfront.

From my  analysis, unfortunately it is very hard to implement the requirement as is as the code couples three concerns very tightly: 1) retreiving records, 2) writing to a csv/tsv file and 3) managing the zip files among others.  At least decoupling needs to happen before this can be revisited.

**Comment by djtfmartin** [comment]
I agree with @javier-molina 

We'd need to scan all records first to determine which fields are populated or have a separate piece of code that effectively "cleaned up" the generated zip file.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
