### ISSUE TITLE
Downloads - JSON statusUrl broken

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#221]
First reported by @PeggyNewman & @raymondben due to broken tests in [ALA4R](https://github.com/AtlasOfLivingAustralia/ALA4R):

> Every time I run the query it returns the same UUID (in ALA4R or browser):
   which just says 'invalidId'. You get the same one.
Query:
http://biocache.ala.org.au/ws/occurrences/offline/download?q=data_resource_uid%3Adr356&email=ala4rtesting%40test.org&reasonTypeId=10&sourceTypeId=2001&esc=%5C&sep=%09&file=data
Returned UUID:
e31173cf-dabc-314c-92bd-466bed114577-1526364677673
I would have thought Biocache would give a different UUID every query.

I've tracked down the issue to being related to serving the `statusUrl` for a download - when the `statusUrl` is requested, the resulting response is always:

    {
      "status": "invalidId"
    }

So there appears to be an issue in looking up the download status info, somewhere around this line:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/75490ceb0ac231af108d1c1381e7701b4b52d0e0/src/main/java/au/org/ala/biocache/web/DownloadController.java#L315

The actual download runs as expected and the email comes through, as does the ZIP download file, which contains the expected number of records. Which is why the UI still works fine, as it doesn't access the JSON output.

**Comment by javier-molina** [comment]
**Current status**
Unfortunately this is is indeed a bug in our current production system.

This has already been fixed in https://github.com/AtlasOfLivingAustralia/biocache-service/commit/258b671658aa5e2f9701187e199b21026ae44bda but we depend on the release of the new infrastructure of biocache-service before the fix can see the light into production.

**Description of Bug**
The status call will report correctly when the job is inQueue or running, however the status will become invalid if the process has finished either successfully or not.

No duplicates UUID can be found, while the prefix of the status ID is the same, the suffix is different for each successive call.  

Still a user should receive either an email with the download file or an error email.

**Workaround**
As a workaround if ALA4R  does not monitor emails it could still monitor the status url and when the status changes from running to invalid it can then try to download the zip file. If the zip file is not available then the process failed.

**Comment by raymondben** [comment]
OK, thanks, we'll try brute-force downloading the zip file as a workaround (no, ALA4R can't monitor the emails). Can you please remind me what the zip URL will look like? Currently we just read whatever URL comes back in the downloadUrl component of the status response, but I can't remember what that looks like (I presume it's something like the statusUrl but with a ".zip" appended, and perhaps a modified path?)

**Comment by raymondben** [comment]
OK, ta - seems straightforward enough. Two last questions - the date component of that string is:
- UTC? Local server time? Local client time?
- the date on which the request was completed? Or date submitted?

**Comment by nickdos** [comment]
Its just the `file` param value, e.g. `&file=records-2018-05-17`

**Comment by javier-molina** [comment]
Server time, the date in which the  download is started, server time is AEST

**Comment by raymondben** [comment]
Yippee, all good, thanks chaps! https://github.com/AtlasOfLivingAustralia/ALA4R/commit/49bbe6913fc7b5f67e6e3d7a4c48c834ec7b2b19

(PS @nickdos - you're right, this is set by the `file` param, which makes it nice and easy!)

**Comment by javier-molina** [comment]
Fixed in code ages ago. Not yet released to prod because of our big release
work.
