### ISSUE TITLE
Fields which are not stored in the index are missing in offline downloads

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#262]
The requirement to use ``download.solr.only=true`` is causing offline downloads which require fields which are not stored in the index to omit the fields during the download process. The offline downloads feature is a core requirement for biocache-service and this must be fixed urgently.

**Comment by djtfmartin** [comment]
Can you list some required fields for this issue ? Doesnt need to complete list.

**Comment by djtfmartin** [comment]
Fixed.

Comparing the headers of the "Legacy" download between Old and New, and there was some missing fields (mainly taxonomy fields). This has now been fixed with this commit:

https://github.com/AtlasOfLivingAustralia/biocache-service/commit/2c521b2a59d935ac5c3df9f3efd55c54e05657e2

The legacy download in the clustered environment now provides all the fields that the old service does plus some fields that should always have been there (e.g. licence, individualCount).
