### ISSUE TITLE
Column name oddities in occurrences and species download

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#34]
1. If I ask for "matched_name" or "lsid" in my list of fields to be returned, I don't get them back.

(try e.g. [http://biocache.ala.org.au/ws/occurrences/index/download?reasonTypeId=10&q=data_resource_uid:dr356&fields=longitude,lsid,matched_name&qa=none](http://biocache.ala.org.au/ws/occurrences/index/download?reasonTypeId=10&q=data_resource_uid:dr356&fields=longitude,lsid,matched_name&qa=none))

2. If I leave the requested fields as their default values, I get the scientific name in a column called scientificName - all good. But if I actually specify the field "scientificName", I get something with all-lower case names and abbreviated genus:

[http://bie.ala.org.au/ws/download?q=genus:Aptenodytes&fields=scientificName](http://bie.ala.org.au/ws/download?q=genus:Aptenodytes&fields=scientificName)

scientificName
"aptenodytes"
"a. forsteri"
"a. patagonicus"

If I ask for "nameComplete", I get what appears to be the correct scientific name.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#86_

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 14:26_


*date:* Wed Jul 16 22:49:08 2014
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Labels:* Biocache

**Comment by nickdos** [comment]
matched_name and lsid are **psuedo** fields - they don't exist in SOLR but are swapped at runtime to a more complex query. Not sure how to deal with this. Possibly we should remove them as psuedo fields and implement in SOLR some way?

**Comment by adam-collins** [comment]
Only stored=true fields can be downloaded. See http://biocache.ala.org.au/ws/index/fields

The exceptions are Cassandra fields that are mapped to SOLR fields internally, e.g. scientificName maps to raw_taxon_name. The default scientificName.p maps to taxon_name. 

One available record lsid field is taxon_concept_lsid. One available matched_name is taxon_name.

In other issues there will be additional mapping for index/fields and a header.csv included in the download listing data.csv header names, the corresponding field requested and some additional information from index/fields.

matched_name and lsid are useful for reducing the size and complexity of some queries due to the processing behind them. Unlike decade, these two search fields are best left as is.

http://api.ala.org.au updated to specify 'stored index field' with a link to the list.
