### ISSUE TITLE
autocomplete causing SOLR performance problem?

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#385]
Both @M-Nicholls and Sebastien noticed that the AODN test portal would allow the autocomplete to work on an initial request but after hitting reset, the autocomplete would be unresponsive. I also saw this and it appears that biocache slows down for subsequent autocomplete requests. Here is an example request: 

https://biocache.ala.org.au/ws/autocomplete/search?q=gonyaulax&fq=species_habitats:%22Marine%22

I'm guessing the initial searches (with only a few characters) may be the expensive queries, so a possible fix is to set a minimum number of letters before searching? This may not be enough though as the example above showed a slow down after repeating the search.

**Comment by nickdos** [comment]
Spoke to @djtfmartin and he confirmed that autocomplete is likely causing the slow downs. Not sure what can be done in short term. He suggested we might use a separate index for autocomplete.

**Comment by nickdos** [comment]
@adam-collins suggests:

> to disable counts, `autocomplete.species.counts.enabled=false`
A recount is triggered if the SOLR index changes. e.g. record added, updated or deleted.
It is supposed to be limited to 1 query at a time for each q+fq+qc (i.e. hub) search.
There is a configurable minimum update time `species.counts.cache.minage=1800000` so the update counts SOLR query does not run continously
A recount query for us was taking about 60s. This is a maximum of 1 SOLR query (taking 60s) for each hub (each qc) using the autocomplete every 30mins.
If autocomplete is slow because it is waiting for the updated count use `species.counts.async.updates=true` to prevent the autocomplete from waiting for the recount to complete.
If it is not clear from the above, when using /autocomplete?q= there should only be one 60s SOLR query no more than every 30mins.

My suggestion is to first try setting `autocomplete.species.counts.enabled=false`, as long as this does not affect SP(?).

**Comment by adam-collins** [comment]
I went with changing the default `species.counts.async.updates=true` in the ansible install. https://github.com/AtlasOfLivingAustralia/ala-install/commit/4715ca991cd08610e0d985ede2bfaba32d48ef47

Using `species.counts.async.updates=true` will, for each biocache-service restart and each unique fq used in the autocomplete, return no results until the counts cache for that fq is built. This differs from `species.counts.async.updates=false` where each unique fq used in the autocomplete can cause a delayed response at most once every 30mins by default.

Counts are required for the autocomplete so that it behaves like the BIE autocomplete while also limiting responses to the fq.

**Comment by ansell** [comment]
I can't reproduce this on `biocache-ws-test` despite working on it for two days, based on a log combining recent autocomplete searches and all autocomplete searches from the retained record which had AODN-Portal as their user agent.

**Comment by nickdos** [comment]
Adam committed a config change to biocache-test that we were hoping would fix it. I think you've successfully tested the fix.

**Comment by M-Nicholls** [comment]
reopen to track AODN testing
