### ISSUE TITLE
New user assertions are not being indexed in real time

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#395]
Previously, when a user flagged an issue, not only was the Cassandra record updated but the SOLR index was dynamically updated to include the assertion. This is no longer happening.

I just annotated a records with geospatial issue and it still appears in searches with `&fq=geospatial_kosher:true` and `&fq=-user_assertions:"50005"` (note the minus sign for inverse fq).

**Comment by ansell** [comment]
The record in question here is:

https://biocache.ala.org.au/occurrences/a0508e6b-6ccb-4a58-8ced-bc7810f66598

**Comment by ansell** [comment]
Not sure what is happening with the search that was used, but the record in Solr currently (7 minutes after this issue was filed) has ` "geospatial_kosher":"false"` when accessed using the admin interface and via biocache-service:

https://biocache-ws.ala.org.au/ws/occurrences/a0508e6b-6ccb-4a58-8ced-bc7810f66598

**Comment by ansell** [comment]
It also has `"user_assertions":"50005"`

**Comment by nickdos** [comment]
biocache-service might be caching results, as SOLR admin shows the record has `geospatialKosher: "false",=`

https://biocache.ala.org.au/ws/occurrences/search?q=id:6844c4c5-3f55-4de8-8d4d-2f8b3d162215

shows: `geospatialKosher: "true"`

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
