### ISSUE TITLE
Groups query to ws/explore produces identical counts

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-service#428]
https://biocache.ala.org.au/ws/explore/groups?q=qid:1580430311543 - using the Explore WS to try to produce a count of groups with a cached query results in all groups showing the same count.

A workaround was identified as using this instead: https://biocache-ws.ala.org.au/ws/occurrence/facets?facets=species_group&q=qid:1580430311543

User query: https://biocache.ala.org.au/ws/explore/groups?wkt=POLYGON((144.61682559304077:-38.25357199711643,144.64051486306508:-38.272980886630116,144.7036862497815:-38.24791009425247,144.71329928689227:-38.204217733842526,144.6882367258573:-38.18398090282429,144.64806796365082:-38.21204113417704,144.61682559304077:-38.25357199711643))

**Comment by brucehyslop** [comment]
The issue appears to be is related to performing a saved/cached query (qid).
This seems to bypass the process of filtering groupings per species_group.

**Comment by brucehyslop** [comment]
The explore groups appends extra parameter the the Solr query to filter out only species for each group however the processing of the cached query `qid` replaces the Solr query (`q`) with the value from the cached query. This effectively clobbers the extra parameters.

Moved the adding of species filters from the Solr query (`q` param) to a Filter Query (`fq` param). The processing of cached queries appends fq params rather than replace.

Also updated the species filter to user `rank_id`, this should improve the accuracy of the results.

**Comment by brucehyslop** [comment]
In investigating the this issue I noticed potential performance issues that might be related to #365.

The groups query [yourAreaView()](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/dae61e23439d75c5f658cc18ee2823004056d486/src/main/java/au/org/ala/biocache/web/ExploreController.java#L175) method iterates through the list of 21 species groups + `ALL_SEPECIES` performing effectively 22 calls to [getYourAreaCount()](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/dae61e23439d75c5f658cc18ee2823004056d486/src/main/java/au/org/ala/biocache/web/ExploreController.java#L228) and 22 Solr queries. 

This could be run with 1 Solr query using a facet pivot. The Solr params are:
```
facet=true
stats=true
facet.pivot={!stats=stat1}species_group
stats.field={!tag=stat1 cardinality=true}taxon_name
```
currently the SearchDAO does not support facet pivots so extra work would need to be performed to handle the response.

**Comment by brucehyslop** [comment]
Note: the number of results will change when regression testing this issue due to the change in the way the rank is filtered.

Prior to this change the filter for species was performed by excluding the following ranks 
 - kingdom
 - phylum
 - class
 - order
 - family
 - genus

this also included occurrence records that are higher then species but not in the above (excluded) list. This has been changed to only exclude records that have a rankId >= Species. 

For regression testing the new result counts should be <= previous results.

**Comment by Rita-C** [comment]
tested, new result counts is <= previous results.
