### ISSUE TITLE
Records with user assertions don't show any assertion data

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#439]
Run a search for records with user assertions - e.g.

https://biocache.ala.org.au/occurrences/search?q=*%3A*&fq=user_assertions%3A%2250005%22&fq=assertion_user_id%3A%2213%22

First record in list does NOT show any assertion data:

https://biocache.ala.org.au/occurrences/2ae8143b-5a80-4908-a59e-c90c6fcc7ecf

Looking at the web service call for assertion data, it is missing the details part (`userAssertions`) of the JSON data:

https://biocache.ala.org.au/assertions/2ae8143b-5a80-4908-a59e-c90c6fcc7ecf

returns:

```json
{
  "userAssertions":[],
  "assertionQueries":[],
  "userAssertionStatus":"50005"
}
```

The fact that the SOLR index knows that the assertion belongs to `userId:13` suggests that biocache-service is not correctly reading the data from Cassandra.

**Comment by nickdos** [comment]
Logs only show this warning:

```
2020-04-03 14:49:21,160 [AsyncAppender-Dispatcher-Thread-2] WARN org.apache.commons.httpclient.HttpMethodBase  (HttpMethodBase.java:682) - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
```

**Comment by nickdos** [comment]
for UUID `2ae8143b-5a80-4908-a59e-c90c6fcc7ecf`, CQL shows:

```
[{"code":10007,"created":"2017-10-24T17:01:01Z","userId":"13","uuid":"6629856a-4a14-4a0c-a38a-e22b2b764487","qastatusName":"QA_UNCONFIRMED","problemAsserted":false,"referenceRowKey":"dr893|http://www.bowerbird.org.au/observations/95629|13|10007","qaStatus":50005,"userDisplayName":"Nicholas dos Remedios","comment":"User has updated BB record to be Poecilometis.","name":"identificationIncorrect"}]
```

**Comment by djtfmartin** [comment]
@nickdos i think i've fixed this.

The primary on the `occ.qa` table consists of 3 parts now - this was changed in the move to cassandra 3.
It consists of `(UUID of the occurrence record, userId, code)`
Looks like there was some old data that wasn't migrated. The old values had the constructed key we store in `occ_uuid `table.

6,275 assertions are now matched up correctly.

There are 630 orphaned assertions. These are assertions i couldn't associate with an existing occurrence record - possibly because the occurrence record was been deleted prior to the migration to cassandra 3 - before the occ_uuid table existed.

**Comment by djtfmartin** [comment]
Still work to be done here as the facet counts dont align with contents of qa (or my previous numbers where incorrect).

<img width="591" alt="Screen Shot 2020-04-05 at 9 32 22 am" src="https://user-images.githubusercontent.com/444897/78470314-624b9200-7720-11ea-8c21-8780b287f72b.png">

**Comment by djtfmartin** [comment]
At the time of writing, there are 8,144 annotations, for 7,498 records.
Of these 7,498 referenced records, only 4,676 are present in the `occ` table, presumably due to record deletions.

So the result of the following query should be 4,676 records (it is currently 3,736)

https://biocache.ala.org.au/occurrences/search?q=*%3A*&fq=user_assertions:*

I've updated the `qa` table and the `occ.userQualityAssertion` and `occ.userAssertionStatus` column which is used to index the data.

These changes should be picked up in the next re-index.

**Comment by djtfmartin** [comment]
This isn't fixed yet. Count still says 3,772.

**Comment by nickdos** [comment]
Could they be deleted assertions (deleted by user)? Would depend on whether they are hard or soft deletes.

**Comment by djtfmartin** [comment]
i'll check that....

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
