### ISSUE TITLE
user-agent not to the log events multi-threaded requests

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/biocache-service#465]
The `user-agent` parameter is not sent to the logger-service when the log event is triggered in a different thread. The issue is because the `user-agent` is added to the Logger via a MDC property however MDC is ThreadLocal.

**Comment by brucehyslop** [comment]
Will pass the `user-agent` down the call stack and send with the log event. 
This depends on https://github.com/AtlasOfLivingAustralia/ala-logger/issues/3 to accept the `user-agent` parameter.

**Comment by nickdos** [comment]
@ansell did you check this is OK in test env?

**Comment by ansell** [comment]
Testing while tailing the logs on `nectar-logger-test` using:

```
tail -f /var/log/tomcat7/catalina.out /var/log/tomcat7/logger.log /var/log/nginx/error.log /var/log/nginx/access.log /var/log/nginx/postdata.log
```

## Occurrence record viewing

```
==> /var/log/nginx/access.log <==
13.54.197.47 - - [08/Jul/2020:10:47:37 +1000] "POST /service/logger HTTP/1.1" 200 464 "-" "undefined" "-" request_time=1.089 upstream_response_time=1.088 upstream_connect_time=0.000 upstream_header_time=1.088 upstream_cache_status=-

==> /var/log/nginx/postdata.log <==
{\x22month\x22:\x22\x22,\x22comment\x22:\x22Viewing Occurrence Record 0dee4e1d-e1f9-44f2-8254-55fa35de30a1\x22,\x22userAgent\x22:\x22\x22,\x22userEmail\x22:\x22Java/1.8.0_252\x22,\x22recordCounts\x22:{\x22dp77\x22:1},\x22userIP\x22:\x223.24.57.181, 3.24.57.181\x22,\x22eventTypeId\x22:1000}
```

- [ ] The two `userIP` values there are for our server, not the original user IP (this may be acceptable behaviour)
- [ ] The `userAgent` is two double-quotes `""`, and the Java User-Agent (not the original User-Agent value) seems to appear in `userEmail` instead.

The `month` is also empty, but it appears that logger-service may be filling that in automatically as it appears in the matching log event at `https://logger-test.ala.org.au/admin/logEvent/show/1047002592`

## Offline downloads

Failed testing an offline download:

```
==> /var/log/nginx/access.log <==
13.54.197.47 - - [08/Jul/2020:10:55:17 +1000] "POST /service/logger HTTP/1.1" 200 4087 "-" "" "-" request_time=0.332 upstream_response_time=0.332 upstream_connect_time=0.004 upstream_header_time=0.328 upstream_cache_status=-

==> /var/log/nginx/postdata.log <==
{\x22comment\x22:\x22\x22,\x22eventTypeId\x22:1002,\x22userIP\x22:\x22127.0.0.1\x22,\x22userAgent\x22:\x22\x22,\x22recordCounts\x22:{\x22dr2428\x22:3788,\x22dp77\x22:3788},\x22userEmail\x22:\x22[REDACTED]@[REDACTED]\x22,\x22month\x22:\x22\x22,\x22reasonTypeId\x22:10,\x22sourceTypeId\x22:0,\x22sourceUrl\x22:\x22https://biocache-ws-test.ala.org.au/ws?q=*:*&fq=data_resource_uid:\x5C\x22dr2428\x5C\x22&start=0&pageSize=0&sort=score&dir=asc&qc=&fl=occurrence_date,country,geospatial_kosher,year,point-0.01,data_resource,taxonomic_kosher,lat_long,record_number,species_guid,state_conservation,occurrence_year,genus_guid,taxon_concept_lsid,occurrence_remarks,point-0.1,rank,data_provider,user_assertions,id,state,assertions,common_name,raw_common_name,order,longitude,basis_of_record,collection_uid,image_url,location_remarks,point-1,sensitive,point-0.0001,identification_verification_status,country_code,license,collectors,month,genus,occurrence_id,ibra,lft,species_group,subspecies,occurrence_details,collection_name,collection_code,rank_id,raw_taxon_name,occurrence_date_end_dt,data_resource_uid,data_hub,latitude,data_provider_uid,type_status,institution_name,collector,imcra,institution_uid,subspecies_guid,rights,taxon_name,class,rgt,grid_ref,catalogue_number,aust_conservation,data_hub_uid,names_and_lsid,point-0.001,photographer_s,coordinate_uncertainty,all_image_url,kingdom,institution_code,raw_type_status,places,multimedia,phylum,species,raw_basis_of_record,family&formattedQuery=*:*&facet=false&email=[REDACTED]@[REDACTED]&reason=&file=records-2020-07-08&fields=data_resource_uid,modified_date,language,license,rightsholder,access_rights,bibliographic_citation,institution_id,collection_id,dataset_id,institution_code,collection_code,dataset_name,owner_institution_code,basis_of_record,dynamic_properties,occurrence_id,catalogue_number,record_number,collector,individual_count,organism_quantity,organism_quantity_type,raw_sex,life_stage,reproductive_condition,behavior,cultivated,establishment_means,occurrence_status,preparations,disposition,associated_media,associated_references,associated_sequences,associated_taxa,other_catalog_numbers,occurrence_remarks,previous_identifications,event_id,field_number,occurrence_date,event_time,start_day_of_year,end_day_of_year,year,month,day,verbatim_event_date,habitat,sampling_protocol,sampling_effort,field_notes,event_remarks,location_id,higher_geography,continent,water_body,island_group,island,country,country_code,state,county,municipality,raw_locality,verbatim_locality,min_elevation_d,max_elevation_d,elevation,min_depth_d,max_depth_d,location_according_to,location_remarks,latitude,longitude,coordinate_uncertainty,coordinate_precision,verbatim_coordinates,raw_latitude,verbatim_latitude,raw_longitude,verbatim_longitude,raw_datum,verbatim_coordinate_system,verbatim_srs,footprint_wkt,footprint_srs,georeferenced_by,georeferenced_date,georeference_protocol,georeference_sources,georeference_verification_status,georeference_remarks,identification_id,identification_qualifier,type_status,identified_by,identified_date,identification_references,identification_verification_status,identification_remarks,taxon_id,scientific_name_id,taxon_concept_lsid,raw_taxon_name,taxon_name,accepted_name_usage,parent_name_usage,original_name_usage,name_published_in,higher_classification,kingdom,phylum,class,order,family,genus,subgenus,specific_epithet,infraspecific_epithet,rank,common_name,nomenclatural_code,taxonomic_status,nomenclatural_status,taxon_remarks,individual_id,identifier_role,species,measurement_id,raw_identification_qualifier,provenance,measurement_determined_by,measurement_determined_date,id,rights,source,measurement_value,relationship_remarks,raw_continent,related_resource_id,measurement_accuracy,raw_basis_of_record,measurement_method,relationship_of_resource,measurement_type,measurement_unit,measurement_remarks&extra=&reasonTypeId=10&sourceTypeId=0&qa=none&dwcHeaders=true\x22}
```

- [ ] The `userAgent` is an empty string `""`. However, this may be an issue with biocache-hubs or downloads-plugin not passing through the original user agent correctly rather than a bug in DownloadService here in biocache-service.
The `userEmail` appeared correctly in this case.

**Comment by brucehyslop** [comment]
The `User-Agent` logged by the logger-service is retrieved from the HTTP `User-Agent` header however this should be same data as the POST body JSON. 

The blank `User-Agent` may be a result of the client app not passing through (as mentioned above).

**Comment by ansell** [comment]
@brucehyslop @nickdos I don't think the priority for this would warrant it delaying testing and CAB approval for the other biocache-service improvements if it comes to that. Fixing biocache-hubs and/or downloads-plugin to forward through the expected User-Agent would likely be a low priority given it has been broken for so long already and isn't relied on for the world-visible logger-service functions at this point.

The removal of the Log4J MDC layer should be a bug fix on its own because MDC doesn't work with multithreading in the way we relied on it to do so before the offline download thread pools were created back in 2016/2017. 

However, the nginx logs above show that biocache-service is passing through the string `undefined` for the HTTP User-Agent header in the Occurrence Record case and an empty value in the other. That doesn't match the JSON being posted where it is an empty string in both cases.

A middle ground to avoid doing further work on this issue could be to redefine it to be "Removing MDC", and then open separate issue here for the `undefined` User-Agent value and on biocache-hubs/downloads-plugin to pass through the original User-Agent value.

**Comment by brucehyslop** [comment]
The biocache-hubs does not pass the `User-Agent` header through the biocache-service
https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/4bc56fefc344e30e0fec8aa749d966e8c08d1ad5/grails-app/services/au/org/ala/biocache/hubs/WebServicesService.groovy#L385-L397

**Comment by brucehyslop** [comment]
I agree with @ansell 

I've checked the logging of Occurrence Records and the email and User-Agent variables had been transposed. I'll fix and double check.

**Comment by brucehyslop** [comment]
`User-Agent` now passed through on "Occurrence Record" case.

Request to `/ws/occurrences/41fcf3f2-fa7b-4ba6-a88c-4ac5240c8aab` results in the following POST to the logger-service.

```
POST /logger-service/service/logger HTTP/1.1
Accept: application/json, application/*+json
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache
Pragma: no-cache
Host: localhost:8180
Connection: keep-alive
Content-Length: 302

{"comment":"Viewing Occurrence Record 41fcf3f2-fa7b-4ba6-a88c-4ac5240c8aab","eventTypeId":1000,"userIP":"0:0:0:0:0:0:0:1","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","recordCounts":{},"userEmail":"","month":""}
```

**Comment by ansell** [comment]
Two issues I opened on the downloads-plugin in the past about the User-Agent issues are:

https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/34

https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/35

It is possible that one or both of those are probably more relevant to biocache-hubs than downloads-plugin

**Comment by nickdos** [comment]
PR has been merged, so can this be moved to QA?

**Comment by ansell** [comment]
Yes, moving it now

**Comment by Rita-C** [comment]
@ansell @brucehyslop , do you want to leave this ticket in QA/waiting for until the downloads-plugin issues being addressed?

**Comment by Rita-C** [comment]
discussed with @ansell and @brucehyslop , moving this one to ready for CAB.
