### ISSUE TITLE
Send log events asynchronously

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#514]
We are currently sending log events synchronously, which blocks responses unnecessarily when logger service is slow.

It would be useful to transform LoggerRestService to make log event submission asynchronous. 

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/40bae4300efb0bc56e84ea71f81a811c2a359ca3/src/main/java/au/org/ala/biocache/service/LoggerRestService.java#L96

**Comment by brucehyslop** [comment]
There are a couple of approaches that we could use to asynchronously log events

1. log events each in a new thread concurrently
2. queue events a process sequentially 

I've done some investigation of the maximum occurrence queries that have been experienced by the` biocache-serivce` on the since access logs have been available in Kibana and found that the max queries has been **~500,000** in an hour (2020-09-25 16:00). Another period of **~250,000** query per hour over a 3 hours window also occurred on 2020-09-29 17:00 - 19:00.

This equates to a max load of **~15 search queries per second**. 

Note the majority of the time the search queries occur at ~3000 / hour (or ~1 / second)

At this heigh logging throughput both approaches may cause issues if the `logger-service` is unable to keep up with the events. 

Option 1 is likely going to flood the logger-service with events.
Option 2 would cause the queue size to grow if the log events are triggered at a faster rate then the logger-service is able to accept.

Since the max search queries to biocache-service are bursty it might be best to query log events and send them sequentially. We could also rate limit the events to further prevent the flooding the logger-service. 

This is a similar approach to the handling of offline downloads.

**Comment by ansell** [comment]
I don't think we want to log all search queries at this point. Being able to turn occurrence record view logging back on could be useful also, but the main issue is not dropping submissions for the offline downloads which we want to stay switched on and give data providers accurate figures about downloads of their records.

Looking at just offline downloads, we sometimes get flooded with a few hundred downloads at a time, but they don't all complete at the same time due to the offline download scheduler executing them slowly.

One implementation strategy could be to use a `BlockingQueue` as the communication between the Offline Download Executor Threads and the Logger Submission thread. If it had a configurable capacity (defaulting to 100 or 1000 for example), then it would not need to block for offline download completion unless the capacity filled up and it would then failsafe (by waiting for logger to become responsive again to let the queue clear). If the download queue does stall Zabbix will alert about the lack of progress and we would look into the issue at that point.

**Comment by nickdos** [comment]
Waiting for PR code review: https://github.com/AtlasOfLivingAustralia/biocache-service/compare/feature/issue-%23514-send-log-events-asynchronously.
