### ISSUE TITLE
Image metadata display

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-service#52]
When displaying images show creator, rights, rightsHolder and license with information drawn from the image metadata (rather than the occurrence record)

**Comment by M-Nicholls** [comment]
test records: http://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr2326

**Comment by djtfmartin** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-hubs#129

**Comment by nickdos** [comment]
Re-opening and adding more details to this issue...

I've had a number of requests for us to provide both the image/sound URL and rights/license info in the SOLR index and it makes sense to have this data available in our API and not to rely on every client to have to do separate requests to lookup this info every time. There are too many implementations (biocache, specimen browser, BIE, pigeonhole tool, specieslist, etc) of this functionality in ALA and external systems to argue that approach. 

Additional check is sound files should also have their URL, rightsHolder, licesnse, etc stored in SOLR index.

Question: should the license by indexed as well? Miles has a string view it should be, as it would allow the user to search for images that are (say) creative commons, without having to go through each record and pulling that info out. Happy to park this feature until we sort out SOLR performance issues.

**Comment by M-Nicholls** [comment]
Being able to search on license type is very useful for finding images of taxa suitable for re-use but not urgent (no one has specifically requested it).  That said, if we're adding the rest of image info to the index it's a good opportunity to include this as well.

**Comment by nickdos** [comment]
I think Dave is concerned with the SOLR index memory usage getting too large and affecting performance. We can add the fields as "stored" but not "indexed" initially and this should not adversely affect search performance. Once the performance issue has been sorted we should be able to change to be "indexed" as well.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-store/commit/820e81a651dd4c87ae181b8c08f14e42087ad110

**Comment by djtfmartin** [comment]
Im not sure its worth indexing rights, rightsHolder, licence fields unless they are using a vocabulary, and out of the 3 fields licence is likely to be the only field we could use a vocabulary for.

rights and rightHolder are free text so im not sure how this will impact the size of the index, or how useful they will be for searching.

**Comment by AlexisTindall** [comment]
I'd like to add my support to Miles' comment that being able to search on licence is really valuable. As a source of openly licensed images, with users that are drawing on data and images for lots of derivative public applications (education, websites, presentations) being able to find images that are licensed for re-use is really handy. 

I recently made a set of mini-field guides for school students on one of our outreach trips, and found the process of finding images, working out whether they were openly licensed or not and gathering attributions quite difficult. 

I can understand the difficulty in indexing rightsHolder, but there are a group of users who would have more confidence in a picture identified and posted by an institution (museum, herbaria, Dept of environment) than one sourced from citizen science, so that is an example of when that might be handy - but I don't believe it's essential.

**Comment by djtfmartin** [comment]
Thanks Alexis.  I agree about on indexing licence provided we can start snapping values to a vocabulary. For provenance information, don't we already have this through the record associations with institutions/collections/data providers ? These associations will be more precise to deal with than the free text values in rights/rightsHolder fields.

**Comment by djtfmartin** [comment]
Closed. Closing historic issue. If this is still a problem, please reopen.
