### ISSUE TITLE
AVH - Spatial filters show IDs, not names in Biocache search

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-service#781]
When searching in AVH, location filters such as IBRA regions/subregions show their ID numbers rather than their names in the list of filters - screenshots below.

Example search: https://avh.ala.org.au/occurrences/search?q=text%3AEremophila&disableAllQualityFilters=true&qc=data_hub_uid%3Adh9&fq=(taxon_name%3A%22Eremophila%20conglomerata%22%20OR%20taxon_name%3A%22Eremophila%20georgei%22%20OR%20taxon_name%3A%22Eremophila%20platythamnos%20subsp.%20exotrachys%22%20OR%20taxon_name%3A%22Eremophila%20platythamnos%20subsp.%20platythamnos%22%20OR%20taxon_name%3A%22Eremophila%20pungens%22%20OR%20taxon_name%3A%22Eremophila%20simulans%22%20OR%20taxon_name%3A%22Eremophila%20simulans%20subsp.%20lapidensis%22%20OR%20taxon_name%3A%22Eremophila%20simulans%20subsp.%20megacalyx%22%20OR%20taxon_name%3A%22Eremophila%20simulans%20subsp.%20simulans%22%20OR%20taxon_name%3A%22Eremophila%20sp.%20Meekatharra%20(D.J.Edinger%204430)%22)#tab_mapView

![Image](https://user-images.githubusercontent.com/57081387/208037563-ab65d3f7-3066-4ea0-8ec2-af121e601976.png)
![Image](https://user-images.githubusercontent.com/57081387/208037564-976b3b17-c667-4de4-a1b6-703081d461ac.png)

Reported in:
https://support.ehelp.edu.au/a/tickets/163945

**Comment by sughics** [comment]
Issue originally suspected to be caused by response from biocache-service `/index/fields` response but upon further investigation noticed that the same application version and configuration on avh-test was showing facet names instead of facets number. i.e working as expected.    
Issue was caused due to old i18n cache. i18n cache has now  been refreshed and the facet names are now appearing as expected. 

@peggynewman  please confirm.

**Comment by timhicks-ala** [comment]
Thanks @sughics - I can confirm the labels are appearing correctly for me, I'll let the affected user know.

The reporting user is also one who reported #779 so I'll let them know we're still working on the fix to that one.
