### ISSUE TITLE
Downloading records for a species list is not working

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocache-service#810]
Clicking download all records from a species list does not trigger the download but returns 404.
<img width="224" alt="image" src="https://user-images.githubusercontent.com/1152259/234430177-5776e500-8628-4bcb-8fe3-55ad28cf789c.png">
It goes to this [link](https://biocache-ws.ala.org.au/ws/occurrences/index/download?q=qid:1682465752845&file=IBRA_Victorian_Midlands_-_Flora&reasonTypeId=10&email=temi.varghese@csiro.au) which fails.

**Comment by adam-collins** [comment]
`/occurrences/index/download` is deprecated. It should trigger the also deprecated `/occurrences/download`.

**Comment by adam-collins** [comment]
Fixed on develop. https://github.com/AtlasOfLivingAustralia/biocache-service/commit/c9f5106a023fbd879e9604719e007ecef5393650

**Comment by sughics** [comment]
Looking further into this.
This will currently not work as the `/occurrences/index/download` has not been added to the api gateway specs yet and download apis in general are protected with JWT requirement on the gateway (but auth is currently optional on biocache-service app itself). TODO below
 

- [ ]  Add the `/occurrences/index/download` specs back to api gateway. 

 

- [ ]  Call index download with a JWT instead of opening a link for file download.

**Comment by sughics** [comment]
Included in release 4.1.1
