### ISSUE TITLE
User assertions: Flaggers should receive personal emails when records they’ve flagged are resolved

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/biocache-service#921]
This feature will clearly indicate to flaggers that they’re making a meaningful difference. When a flagger has their flag resolved, they should receive an email very explicitly indicating this. This could be done the next day after the resolution, or one summary email per week, doesn’t matter. The important thing is that flaggers are actually aware the records they’re flagging are being addressed. 
The current system is terrible. When you flag a record, there is a checkbox that says ‘Notify me when records I have annotated are updated’. There are three problems, however:
i) It’s unticked by default, so easy to miss
ii) if you do tick this box, the email you receive is quite generic
iii) if you already subscribe to the daily email notifying of new flags + flag resolutions, ticking this box causes a highly irritating glitch where you keep getting spammed by the exact same email being sent to you every single day (this happened to me for quite a while until I figured out the cause).
The very simple solution here is to remove this checkbox, and always send an email to people when their flags are resolved (but obviously not one email per resolution, a summary email of some kind if required, at whatever temporal resolution is appropriate). 

cc @tmesaglio for testing

**Comment by adam-collins** [comment]
There is a misunderstanding with the "My Annotations" alerts as it is currently implemented. I believe it sends you an email for all alerts you have annotated, and I suspect it does not filter anything. Given this misunderstanding it is appropriate today that (i) remains unticked because it results in (iii).

The planned update to "My Annotations" addresses (ii), that is, a filter to include only records with a change. The email will also include more information.

This will be continued at https://github.com/AtlasOfLivingAustralia/alerts/issues/294
